name: Full Project Lint

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint-frontend:
    name: Lint React Frontend
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'
      - name: Install frontend dependencies
        working-directory: client
        run: npm install
      - name: Run ESLint
        working-directory: client
        run: npm run lint

  lint-backend:
    name: Lint Flask Backend
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install backend dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r server/requirements.txt
          pip install flake8
      - name: Run flake8
        working-directory: server
        run: flake8 .
